### ISSUE TITLE
can not see notification and also service does not run

### ISSUE THREAD

**Issue by leonardozanarella** [SeptiyanAndika/simple-android-lockscreen-ads#2]
hello, 
I've that error:
D/LockscreenService: LockscreenService onStartCommand intent  existed
I can see it on my Run tab,
The service starts, but the notification has some problems
Can you help me integrating your system?
Thanks.
LZ

**Comment by SeptiyanAndika** [comment]
hi @leonardozanarella , i think for notification, must update new API.
you can try debug on method showNotification, in file LockscreenService.java
https://github.com/SeptiyanAndika/simple-android-lockscreen-ads/blob/master/app/src/main/java/me/andika/lockscreen/utils/LockscreenService.java#L107

Thanks
