### ISSUE TITLE
It is impossible to create a secure lockscreen app without root/ADB.

### ISSUE THREAD

**Issue by buffermet** [SeptiyanAndika/simple-android-lockscreen-ads#3]
Not even an Accessibility Service app can lock the phone.

I can easily bypass this lockscreen by quickly pressing the power button and then the home button.

My comment below explains how to create a secure custom lockscreen.

**Comment by buffermet** [comment]
# Update

It is possible to use `startLockTask()` **without** triggering a toast or giant "got it" prompt.

You will need ADB to do this:

On your android device there is a file called `device_policies.xml` in `/data/system`, if you change this file, you can enable your app to become a secure lockscreen.

All you have to add is `<lock-task-component name="com.my.app.name" />`.

This is an example of the XML file:

```xml
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<policies setup-complete="true">
    <lock-task-component name="com.my.app.name" />
</policies>
```

That's literally all you have to do.

You can enable certain features that are normally hidden in lockTask mode (such as the status bar) using `lock-task-features` tag.

Happy days

**Comment by SeptiyanAndika** [comment]
Thanks @yungtravla for the update.
